# copied from https://github.com/VeriFIT/mata/blob/84590550390b0d4003c83cd618c532b1959c752a/.github/workflows/ubuntu.yml

name: Ubuntu (build-&-test)

on:
  push:
    branches: 
      - master 
      - devel
  pull_request:
    branches: 
      - master 
      - devel
  # allows to run the action from GitHub UI
  workflow_dispatch:


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Unix dependencies 
      - run: sudo wget -O /etc/apt/trusted.gpg.d/lrde.gpg https://www.lrde.epita.fr/repo/debian.gpg
      - run: sudo echo 'deb http://www.lrde.epita.fr/repo/debian/ unstable/' >> /etc/apt/sources.list
      - run: sudo apt-get update
      - run: sudo apt-get install -y spot libspot-dev python3-spot
      - name: Compile release
        run: make release
      - name: Test release
        run: make test
